export const GET_TOKEN = 'GET_TOKEN';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_USER_INFO = 'GET_USER_INFO';
export const ADD_SUCCESS_MESSAGE = 'ADD_SUCCESS_MESSAGE';
export const ADD_ERROE_MESSAGE = 'ADD_ERROE_MESSAGE';
export const REMOVE_SUCCESS_MESSAGE = 'REMOVE_SUCCESS_MESSAGE';
export const REMOVE_ERROE_MESSAGE = 'REMOVE_ERROE_MESSAGE';
export const TOGGLE_MINIMIZE_MENUBAR = 'TOGGLE_MINIMIZE_MENUBAR';
export const SET_GLOBAL_ACTION = 'SET_GLOBAL_ACTION';

// 系统通用类型
export const CHANGE_LOADING_STATE = 'CHANGE_LOADING_STATE';
